/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e2ed",
        "primary-fixed": "#dbe1ff",
        "muted-steel": "#475569",
        "on-background": "#191b23",
        "surface-container": "#ededf9",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f0fb",
        "primary-container": "#2563eb",
        "outline": "#737686",
        "surface-container-highest": "#e1e2ed",
        "on-tertiary-fixed": "#3d0317",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "frosted-surface": "rgba(255, 255, 255, 0.65)",
        "surface-container-high": "#e7e7f3",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed": "#170065",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d7",
        "background-twilight-start": "#6D5CE6",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed-variant": "#4129b9",
        "surface-container-low": "#f3f3fe",
        "tertiary-fixed": "#ffd9df",
        "inverse-primary": "#b4c5ff",
        "tertiary-fixed-dim": "#ffb1c0",
        "surface-dim": "#d9d9e5",
        "background": "#faf8ff",
        "on-surface-variant": "#434655",
        "surface-tint": "#0053db",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e4dfff",
        "background-twilight-end": "#FFA0B4",
        "on-surface": "#191b23",
        "charcoal-ink": "#0F172A",
        "on-primary-container": "#eeefff",
        "secondary": "#5744cf",
        "secondary-fixed-dim": "#c7bfff",
        "electric-ocean": "#2563EB",
        "on-tertiary-container": "#ffecee",
        "surface": "#faf8ff",
        "primary": "#004ac6",
        "secondary-container": "#705fe9",
        "whisper-border": "rgba(255, 255, 255, 0.4)",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-container": "#fffbff",
        "tertiary": "#873d50",
        "surface-bright": "#faf8ff",
        "tertiary-container": "#a45567",
        "inverse-surface": "#2e3039",
        "on-tertiary-fixed-variant": "#752f41"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "panel-padding": "32px",
        "gutter": "24px",
        "container-max": "1440px",
        "stack-gap": "16px"
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "code-md": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Outfit"],
        "display-lg-mobile": ["Outfit"],
        "display-lg": ["Outfit"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "code-md": ["14px", { lineHeight: "1.5", fontWeight: "450" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.1", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
